# Generated by Django 3.1.12 on 2021-06-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='pre_time',
            new_name='prep_time',
        ),
    ]
