# Generated by Django 3.1.12 on 2021-07-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210701_0110'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipes_rec_name_891f25_idx',
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name', 'calories'], name='recipes_rec_name_e6123b_idx'),
        ),
    ]
